name: ghsci
channels:
  - conda-forge
dependencies:
  - python
  - osmnx=1.5.* # OpenStreetMap network retrieval and analysis
  - pandas=2.1.*
  - fpdf2=2.7.* # pdf templating
  - sqlalchemy=1.4.* # SQL connectivity with PostgreSQL
  - nicegui=1.4.22 # web app framework
  - cryptography=42.0.*,>=42.0.4
  - requests=2.31.*
  - tornado>=6.3.*
  - fonttools=4.43.*
  - jupyterlab=4.0.* # code notebooks / web interface
  - jupyter-lsp=2.2.*
  - urllib3=2.0.*
  - pillow=10.3.*
  - pip>=24.*
  - pyrosm=0.6.* # possible alternate OSM/network retrieval
  - orjson==3.9.*,>=3.9.15
  - idna>=3.7
  - openpyxl
  - babel
  - cartopy
  - contextily # basemaps and map styling
  - ipywidgets
  - geoalchemy2 # Geometry datatype extension for SQL Alchemy
  - pandana # network analysis using Pandas
  - rasterio # raster data reading
  - pygeometa # metadata templating tools
  - psycopg2 # PostgreSQL connection
  - tqdm # Progress bar
  - pyyaml # YAML parsing
  - websockets
