name: Test
on:
  pull_request: { branches: main }
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull and launch GHSCI software and run tests
      run: |
        sudo docker compose -f .test-compose.yml run ghsci
        echo "log=$(cat '/home/ghsci/process/data/_study_region_outputs/example_ES_Las_Palmas_2023/__Las Palmas de Gran Canaria__example_ES_Las_Palmas_2023_processing_log.txt')" >> $GITHUB_OUTPUT
